# All page text for deepinkcode.com, per language.
# Edit text here, then run:  python3 _src/build.py
# Languages: en (default), da, nl, sv, no

LANG_ORDER = ["en", "da", "nl", "sv", "no"]

LANGS = {
    "en": {
        "prefix": "", "html": "en", "og": "en_US", "name": "English",
        "gp_badge": ("google-play-en.png", "Get it on Google Play", 134),
        "as_alt": "Download on the App Store",
        "nav_apps": "Apps", "nav_support": "Support", "nav_privacy": "Privacy",
        "privacy_url": "/privacy-policy-website/",
        "country": "Denmark",
        "read_more": "Read more →",
        "screenshots": "Screenshots", "video": "See it in action",
        "video_note": "The video is played from YouTube when you press play.",
        "play": "Play video",
        "how": "How it works", "features": "Features",
        "faq": "Frequently asked questions", "more": "More word game solvers",
        "icon": "icon",
    },
    "da": {
        "prefix": "/da", "html": "da", "og": "da_DK", "name": "Dansk",
        "gp_badge": ("google-play-da.png", "Nu på Google Play", 135),
        "as_alt": "Hent i App Store",
        "nav_apps": "Apps", "nav_support": "Support", "nav_privacy": "Privatliv",
        "privacy_url": "/da/privatlivspolitik/",
        "country": "Danmark",
        "read_more": "Læs mere →",
        "screenshots": "Skærmbilleder", "video": "Se den i aktion",
        "video_note": "Videoen afspilles fra YouTube, når du trykker på afspil.",
        "play": "Afspil video",
        "how": "Sådan virker det", "features": "Funktioner",
        "faq": "Ofte stillede spørgsmål", "more": "Flere ordspil-hjælpere",
        "icon": "icon",
    },
    "nl": {
        "prefix": "/nl", "html": "nl", "og": "nl_NL", "name": "Nederlands",
        "gp_badge": ("google-play-en.png", "Ontdek het op Google Play", 134),
        "as_alt": "Download in de App Store",
        "nav_apps": "Apps", "nav_support": "Support", "nav_privacy": "Privacy",
        "privacy_url": "/privacy-policy-website/",
        "country": "Denemarken",
        "read_more": "Lees meer →",
        "screenshots": "Screenshots", "video": "Bekijk hoe het werkt",
        "video_note": "De video wordt pas van YouTube geladen als je op afspelen drukt.",
        "play": "Video afspelen",
        "how": "Zo werkt het", "features": "Functies",
        "faq": "Veelgestelde vragen", "more": "Meer woordspel-hulpjes",
        "icon": "icoon",
    },
    "sv": {
        "prefix": "/sv", "html": "sv", "og": "sv_SE", "name": "Svenska",
        "gp_badge": ("google-play-en.png", "Ladda ned på Google Play", 134),
        "as_alt": "Hämta i App Store",
        "nav_apps": "Appar", "nav_support": "Support", "nav_privacy": "Integritet",
        "privacy_url": "/privacy-policy-website/",
        "country": "Danmark",
        "read_more": "Läs mer →",
        "screenshots": "Skärmbilder", "video": "Se hur det fungerar",
        "video_note": "Videon spelas upp från YouTube när du trycker på spela.",
        "play": "Spela video",
        "how": "Så fungerar det", "features": "Funktioner",
        "faq": "Vanliga frågor", "more": "Fler ordspelshjälpare",
        "icon": "ikon",
    },
    "no": {
        "prefix": "/no", "html": "no", "og": "nb_NO", "name": "Norsk",
        "gp_badge": ("google-play-en.png", "Last ned på Google Play", 134),
        "as_alt": "Last ned i App Store",
        "nav_apps": "Apper", "nav_support": "Støtte", "nav_privacy": "Personvern",
        "privacy_url": "/privacy-policy-website/",
        "country": "Danmark",
        "read_more": "Les mer →",
        "screenshots": "Skjermbilder", "video": "Se hvordan det virker",
        "video_note": "Videoen spilles av fra YouTube når du trykker på spill av.",
        "play": "Spill av video",
        "how": "Slik fungerer det", "features": "Funksjoner",
        "faq": "Ofte stilte spørsmål", "more": "Flere ordspillhjelpere",
        "icon": "ikon",
    },
}

HOME = {
    "en": {
        "title": "DeepInkCode – Wordfeud, Words With Friends & Scrabble GO solvers",
        "desc": "DeepInkCode makes ad-free solver apps for Wordfeud, Words With Friends and Scrabble GO. Take a screenshot, and the app finds the highest-scoring moves for you.",
        "h1": "Word game solvers that read your board",
        "lead": "DeepInkCode makes ad-free solver apps for Wordfeud, Words With Friends and Scrabble GO. Take a screenshot, and the app finds the highest-scoring moves for you.",
        "hero_alt": "Wordfeud Solver on a phone",
    },
    "da": {
        "title": "DeepInkCode – Wordfeud, Words With Friends & Scrabble GO solvers",
        "desc": "DeepInkCode laver reklamefri solver-apps til Wordfeud, Words With Friends og Scrabble GO. Tag et skærmbillede, og appen finder de træk, der giver flest point.",
        "h1": "Ordspil-hjælpere, der læser dit bræt",
        "lead": "DeepInkCode laver reklamefri solver-apps til Wordfeud, Words With Friends og Scrabble GO. Tag et skærmbillede, og appen finder de træk, der giver flest point.",
        "hero_alt": "Wordfeud Solver på en telefon",
    },
    "nl": {
        "title": "DeepInkCode – Wordfeud hulp, Words With Friends & Scrabble GO",
        "desc": "DeepInkCode maakt advertentievrije hulp-apps voor Wordfeud, Words With Friends en Scrabble GO. Maak een screenshot en de app vindt de zetten met de meeste punten.",
        "h1": "Woordspel-hulp die je bord leest",
        "lead": "DeepInkCode maakt advertentievrije hulp-apps voor Wordfeud, Words With Friends en Scrabble GO. Maak een screenshot en de app vindt de zetten met de meeste punten.",
        "hero_alt": "Wordfeud Solver op een telefoon",
    },
    "sv": {
        "title": "DeepInkCode – Wordfeud-hjälp, Words With Friends & Scrabble GO",
        "desc": "DeepInkCode gör reklamfria hjälpappar för Wordfeud, Words With Friends och Scrabble GO. Ta en skärmbild så hittar appen dragen som ger flest poäng.",
        "h1": "Ordspelshjälp som läser din spelplan",
        "lead": "DeepInkCode gör reklamfria hjälpappar för Wordfeud, Words With Friends och Scrabble GO. Ta en skärmbild så hittar appen dragen som ger flest poäng.",
        "hero_alt": "Wordfeud Solver på en mobil",
    },
    "no": {
        "title": "DeepInkCode – Wordfeud-hjelp, Words With Friends & Scrabble GO",
        "desc": "DeepInkCode lager reklamefrie hjelpeapper for Wordfeud, Words With Friends og Scrabble GO. Ta et skjermbilde, så finner appen trekkene som gir flest poeng.",
        "h1": "Ordspillhjelp som leser brettet ditt",
        "lead": "DeepInkCode lager reklamefrie hjelpeapper for Wordfeud, Words With Friends og Scrabble GO. Ta et skjermbilde, så finner appen trekkene som gir flest poeng.",
        "hero_alt": "Wordfeud Solver på en mobil",
    },
}

SUPPORT = {
    "en": {
        "title": "Support – DeepInkCode", "desc": "Contact DeepInkCode support.",
        "h1": "Support",
        "lead": "Questions, problems with a purchase or ideas for the apps? Write to us and we will get back to you.",
        "h2": "Before you write",
        "items": [
            "Take the screenshot without zooming in on the board.",
            "In Words With Friends, turn off animated tiles for the best recognition.",
            "Purchases are handled by Google Play or the App Store. To restore a purchase, use “Restore purchases” in the app with the same account you bought it on.",
            "Please include the app name, your device and a screenshot of the problem if possible.",
        ],
    },
    "da": {
        "title": "Support – DeepInkCode", "desc": "Kontakt DeepInkCode support.",
        "h1": "Support",
        "lead": "Spørgsmål, problemer med et køb eller idéer til apps'ene? Skriv til os, så vender vi tilbage.",
        "h2": "Før du skriver",
        "items": [
            "Tag skærmbilledet uden at zoome ind på brættet.",
            "I Words With Friends giver det den bedste genkendelse at slå animerede brikker fra.",
            "Køb håndteres af Google Play eller App Store. Brug “Gendan køb” i appen med den konto, du købte på.",
            "Skriv gerne appens navn, din telefonmodel og vedhæft et skærmbillede af problemet.",
        ],
    },
    "nl": {
        "title": "Support – DeepInkCode", "desc": "Neem contact op met DeepInkCode support.",
        "h1": "Support",
        "lead": "Vragen, problemen met een aankoop of ideeën voor de apps? Stuur ons een bericht, dan nemen we contact met je op.",
        "h2": "Voordat je schrijft",
        "items": [
            "Maak het screenshot zonder in te zoomen op het bord.",
            "Zet in Words With Friends geanimeerde letters uit voor de beste herkenning.",
            "Aankopen worden afgehandeld door Google Play of de App Store. Gebruik “Aankopen herstellen” in de app met hetzelfde account waarmee je hebt gekocht.",
            "Vermeld de naam van de app, je toestel en stuur indien mogelijk een screenshot van het probleem mee.",
        ],
    },
    "sv": {
        "title": "Support – DeepInkCode", "desc": "Kontakta DeepInkCode support.",
        "h1": "Support",
        "lead": "Frågor, problem med ett köp eller idéer till apparna? Skriv till oss så återkommer vi.",
        "h2": "Innan du skriver",
        "items": [
            "Ta skärmbilden utan att zooma in på spelplanen.",
            "I Words With Friends får du bäst igenkänning om du stänger av animerade brickor.",
            "Köp hanteras av Google Play eller App Store. Använd ”Återställ köp” i appen med samma konto som du köpte med.",
            "Skriv gärna appens namn, vilken telefon du har och bifoga en skärmbild av problemet.",
        ],
    },
    "no": {
        "title": "Støtte – DeepInkCode", "desc": "Kontakt DeepInkCode støtte.",
        "h1": "Støtte",
        "lead": "Spørsmål, problemer med et kjøp eller ideer til appene? Skriv til oss, så svarer vi deg.",
        "h2": "Før du skriver",
        "items": [
            "Ta skjermbildet uten å zoome inn på brettet.",
            "I Words With Friends får du best gjenkjenning hvis du slår av animerte brikker.",
            "Kjøp håndteres av Google Play eller App Store. Bruk «Gjenopprett kjøp» i appen med den samme kontoen du kjøpte med.",
            "Skriv gjerne appens navn, hvilken telefon du har, og legg ved et skjermbilde av problemet.",
        ],
    },
}

# Features shared by all apps (per language)
FEATURES = {
    "en": ["Reads the board automatically from a screenshot (OCR)",
           "Solutions ranked by points, with exact placement",
           "Shows how many tiles are left in the game in total – in the bag plus on your opponent’s rack",
           "Up-to-date dictionaries", "No ads",
           "Free to try, with Pro Lifetime and Pro Subscription upgrades"],
    "da": ["Læser brættet automatisk fra et skærmbillede (OCR)",
           "Løsninger sorteret efter point, med præcis placering",
           "Viser hvor mange brikker der er tilbage i spillet i alt – i posen plus hos modstanderen",
           "Opdaterede ordbøger", "Ingen reklamer",
           "Gratis at prøve, med Pro Lifetime og Pro-abonnement"],
    "nl": ["Leest het bord automatisch uit een screenshot (OCR)",
           "Oplossingen gesorteerd op punten, met de exacte plek op het bord",
           "Laat zien hoeveel letters er in totaal nog over zijn – in de zak plus op het rekje van je tegenstander",
           "Actuele woordenlijsten", "Geen advertenties",
           "Gratis te proberen, met Pro Lifetime en Pro-abonnement"],
    "sv": ["Läser spelplanen automatiskt från en skärmbild (OCR)",
           "Lösningar sorterade efter poäng, med exakt placering",
           "Visar hur många brickor som är kvar i spelet totalt – i påsen plus hos motståndaren",
           "Uppdaterade ordlistor", "Ingen reklam",
           "Gratis att prova, med Pro Lifetime och Pro-prenumeration"],
    "no": ["Leser brettet automatisk fra et skjermbilde (OCR)",
           "Løsninger sortert etter poeng, med nøyaktig plassering",
           "Viser hvor mange brikker som er igjen i spillet totalt – i posen pluss hos motstanderen",
           "Oppdaterte ordlister", "Ingen reklame",
           "Gratis å prøve, med Pro Lifetime og Pro-abonnement"],
}

PRIVACY_FAQ = {
    "en": ("Are my screenshots uploaded anywhere?", "No. Screenshots are only used to read the board and are never sent anywhere. The app can delete them for you afterwards."),
    "da": ("Bliver mine skærmbilleder sendt nogen steder hen?", "Nej. Skærmbillederne bruges kun til at læse brættet og sendes aldrig videre. Appen kan slette dem bagefter."),
    "nl": ("Worden mijn screenshots ergens naartoe gestuurd?", "Nee. Screenshots worden alleen gebruikt om het bord te lezen en worden nergens naartoe gestuurd. De app kan ze daarna voor je verwijderen."),
    "sv": ("Skickas mina skärmbilder någonstans?", "Nej. Skärmbilderna används bara för att läsa spelplanen och skickas aldrig vidare. Appen kan radera dem åt dig efteråt."),
    "no": ("Blir skjermbildene mine sendt noe sted?", "Nei. Skjermbildene brukes bare til å lese brettet og sendes aldri videre. Appen kan slette dem for deg etterpå."),
}

PRICE_FAQ = {
    "en": "It is free to download and try. Upgrade to Pro Lifetime – one payment, no subscription – or to Pro Subscription.",
    "da": "Den er gratis at hente og prøve. Opgradér til Pro Lifetime – én betaling, intet abonnement – eller til Pro-abonnement.",
    "nl": "Je kunt de app gratis downloaden en proberen. Upgrade naar Pro Lifetime – één betaling, geen abonnement – of naar een Pro-abonnement.",
    "sv": "Den är gratis att ladda ned och prova. Uppgradera till Pro Lifetime – en betalning, ingen prenumeration – eller till Pro-prenumeration.",
    "no": "Den er gratis å laste ned og prøve. Oppgrader til Pro Lifetime – én betaling, ikke noe abonnement – eller til Pro-abonnement.",
}

APP_ORDER = ["wordfeud-solver", "words-with-friends-solver", "scrabble-go-cheat"]

APPS = {
  "wordfeud-solver": {
    "name": "Wordfeud Solver", "cls": "wordfeud", "img": "wordfeud", "os": "Android, iOS",
    "gp": "https://play.google.com/store/apps/details?id=com.deepinkcode.wordfeudsolver",
    "as": "https://apps.apple.com/app/wordfeud-solver/id6754640376",
    "video": "SkoLrsQ0rak",
    "shots_localized": {"da": "wordfeud-da"},
    "game": "Wordfeud",
    "en": {
      "title": "Wordfeud Solver – Find the Best Word from a Screenshot",
      "desc": "Wordfeud Solver reads your board from a screenshot and shows the highest-scoring words and where to play them. A Wordfeud helper for iPhone and Android. No ads.",
      "tagline": "Find the highest-scoring Wordfeud move from a single screenshot.",
      "intro": "Ever find yourself stuck on a challenging Wordfeud board, searching for the perfect word to play? Wordfeud Solver reads your board from a screenshot and shows you the best moves, ranked by points.",
      "extra": "Think of it as a Wordfeud helper and word finder in one: no typing in letters or rebuilding the board by hand. You get the best Wordfeud words for your exact board and rack, sorted by score.",
      "note": "",
      "shots": ["Find the best word", "Import your board", "See your highest-scoring moves", "See the tiles left", "Choose the right dictionary"],
      "steps": [("Take a screenshot", "Take a screenshot in the Wordfeud app. Make sure not to zoom in on the board."),
                ("Import the screenshot", "Open Wordfeud Solver. Your latest screenshot is imported automatically. If not, tap “Import” and choose the screenshot."),
                ("Pick your move", "Browse the ranked solutions to see their points and where to place them on the board.")],
      "disclaimer": "Wordfeud Solver is an independent app and is not affiliated with or endorsed by the makers of Wordfeud.",
      "faq": [("Do I have to type in my letters?", "No. Take a screenshot in Wordfeud and the solver reads both the board and your rack automatically."),
              ("Does it work on iPhone and Android?", "Yes. Wordfeud Solver is available on the App Store and on Google Play."),
              ("Which dictionary does it use?", "You choose the dictionary that matches the language of your Wordfeud game in the app’s settings."),
              ("Is Wordfeud Solver free?", None)],
    },
    "da": {
      "title": "Wordfeud Solver – Wordfeud-hjælp der finder det bedste ord",
      "desc": "Wordfeud Solver læser dit bræt fra et skærmbillede og viser de ord, der giver flest point, og hvor de skal ligge. Wordfeud-hjælper til iPhone og Android. Ingen reklamer.",
      "tagline": "Find det bedste Wordfeud-træk ud fra ét skærmbillede.",
      "intro": "Sidder du fast på et svært Wordfeud-bræt og leder efter det perfekte ord? Wordfeud Solver læser dit bræt fra et skærmbillede og viser de bedste træk, sorteret efter point.",
      "extra": "Den er Wordfeud-hjælper og ordfinder i én: Du skal ikke taste bogstaver ind eller bygge brættet op i hånden. Du får de bedste Wordfeud-ord til netop dit bræt og dine brikker, sorteret efter point.",
      "note": "",
      "shots": ["Find det bedste ord", "Importér dit spillebræt", "Se træk med flest point", "Se brikker tilbage", "Vælg den rigtige ordbog"],
      "steps": [("Tag et skærmbillede", "Tag et skærmbillede i Wordfeud-appen. Sørg for ikke at zoome ind på brættet."),
                ("Importér skærmbilledet", "Åbn Wordfeud Solver. Dit seneste skærmbillede importeres automatisk. Hvis ikke, så tryk på “Importér” og vælg skærmbilledet."),
                ("Vælg dit træk", "Bladr gennem de rangerede løsninger og se point og placering på brættet.")],
      "disclaimer": "Wordfeud Solver er en uafhængig app og er ikke tilknyttet eller godkendt af udviklerne af Wordfeud.",
      "faq": [("Skal jeg taste mine bogstaver ind?", "Nej. Tag et skærmbillede i Wordfeud, så læser appen både brættet og dine brikker automatisk."),
              ("Virker den på iPhone og Android?", "Ja. Wordfeud Solver findes i App Store og på Google Play."),
              ("Hvilken ordbog bruger den?", "Du vælger den ordbog, der passer til sproget i dit Wordfeud-spil, i appens indstillinger."),
              ("Er Wordfeud Solver gratis?", None)],
    },
    "nl": {
      "title": "Wordfeud Solver – Wordfeud hulp: vind het beste woord",
      "desc": "Wordfeud Solver leest je bord uit een screenshot en toont de woorden met de meeste punten en waar je ze legt. Wordfeud hulp en woordzoeker voor iPhone en Android.",
      "tagline": "Vind de Wordfeud-zet met de meeste punten vanuit één screenshot.",
      "intro": "Zit je vast op een lastig Wordfeud-bord en zoek je het perfecte woord? Wordfeud Solver leest je bord uit een screenshot en laat de beste zetten zien, gesorteerd op punten.",
      "extra": "Wordfeud hulp en woordzoeker in één: je hoeft geen letters in te typen of het bord na te bouwen. Je krijgt de beste Wordfeud-woorden voor precies jouw bord en letters, gesorteerd op punten. Ook handig als Wordfeud cheat wanneer je echt vastzit.",
      "note": "",
      "shots": ["Vind het beste woord", "Importeer je bord", "Bekijk de zetten met de meeste punten", "Bekijk de resterende letters", "Kies de juiste woordenlijst"],
      "steps": [("Maak een screenshot", "Maak een screenshot in de Wordfeud-app. Zoom niet in op het bord."),
                ("Importeer het screenshot", "Open Wordfeud Solver. Je nieuwste screenshot wordt automatisch geïmporteerd. Zo niet, tik dan op “Importeren” en kies het screenshot."),
                ("Kies je zet", "Blader door de gesorteerde oplossingen en zie de punten en waar je het woord op het bord legt.")],
      "disclaimer": "Wordfeud Solver is een onafhankelijke app en is niet verbonden aan of goedgekeurd door de makers van Wordfeud.",
      "faq": [("Moet ik mijn letters intypen?", "Nee. Maak een screenshot in Wordfeud en de app leest zowel het bord als je letters automatisch."),
              ("Werkt het op iPhone en Android?", "Ja. Wordfeud Solver is beschikbaar in de App Store en op Google Play."),
              ("Werkt het met de Nederlandse woordenlijst?", "Je kiest in de instellingen van de app de woordenlijst die past bij de taal van je Wordfeud-spel."),
              ("Is Wordfeud Solver gratis?", None)],
    },
    "sv": {
      "title": "Wordfeud Solver – Wordfeud-hjälp som hittar bästa ordet",
      "desc": "Wordfeud Solver läser din spelplan från en skärmbild och visar orden som ger flest poäng och var de ska läggas. Wordfeud-hjälp och ordfinnare för iPhone och Android.",
      "tagline": "Hitta Wordfeud-draget som ger flest poäng från en enda skärmbild.",
      "intro": "Sitter du fast på en knepig Wordfeud-plan och letar efter det perfekta ordet? Wordfeud Solver läser din spelplan från en skärmbild och visar de bästa dragen, sorterade efter poäng.",
      "extra": "Wordfeud-hjälp och ordfinnare i ett: du behöver inte skriva in bokstäver eller bygga upp spelplanen för hand. Du får de bästa Wordfeud-orden för just din spelplan och dina brickor, sorterade efter poäng – smidigare än att fuska med en vanlig ordlista.",
      "note": "",
      "shots": ["Hitta det bästa ordet", "Importera din spelplan", "Se dragen med flest poäng", "Se brickor kvar", "Välj rätt ordlista"],
      "steps": [("Ta en skärmbild", "Ta en skärmbild i Wordfeud-appen. Zooma inte in på spelplanen."),
                ("Importera skärmbilden", "Öppna Wordfeud Solver. Din senaste skärmbild importeras automatiskt. Om inte, tryck på ”Importera” och välj skärmbilden."),
                ("Välj ditt drag", "Bläddra bland de sorterade lösningarna och se poäng och placering på spelplanen.")],
      "disclaimer": "Wordfeud Solver är en fristående app och är inte knuten till eller godkänd av skaparna av Wordfeud.",
      "faq": [("Måste jag skriva in mina bokstäver?", "Nej. Ta en skärmbild i Wordfeud så läser appen både spelplanen och dina brickor automatiskt."),
              ("Fungerar den på iPhone och Android?", "Ja. Wordfeud Solver finns i App Store och på Google Play."),
              ("Fungerar den med svenska ordlistan?", "Du väljer den ordlista som passar språket i ditt Wordfeud-spel i appens inställningar."),
              ("Är Wordfeud Solver gratis?", None)],
    },
    "no": {
      "title": "Wordfeud Solver – Wordfeud-hjelp som finner beste ord",
      "desc": "Wordfeud Solver leser brettet ditt fra et skjermbilde og viser ordene som gir flest poeng og hvor de skal legges. Wordfeud-hjelp og ordfinner for iPhone og Android.",
      "tagline": "Finn Wordfeud-trekket som gir flest poeng fra ett enkelt skjermbilde.",
      "intro": "Står du fast på et vanskelig Wordfeud-brett og leter etter det perfekte ordet? Wordfeud Solver leser brettet ditt fra et skjermbilde og viser de beste trekkene, sortert etter poeng.",
      "extra": "Wordfeud-hjelp og ordfinner i ett: du trenger ikke skrive inn bokstaver eller bygge opp brettet for hånd. Du får de beste Wordfeud-ordene for akkurat ditt brett og dine brikker, sortert etter poeng – enklere enn å jukse med en vanlig ordliste.",
      "note": "",
      "shots": ["Finn det beste ordet", "Importer brettet ditt", "Se trekkene med flest poeng", "Se brikker igjen", "Velg riktig ordliste"],
      "steps": [("Ta et skjermbilde", "Ta et skjermbilde i Wordfeud-appen. Ikke zoom inn på brettet."),
                ("Importer skjermbildet", "Åpne Wordfeud Solver. Det siste skjermbildet ditt importeres automatisk. Hvis ikke, trykk på «Importer» og velg skjermbildet."),
                ("Velg trekket ditt", "Bla gjennom de sorterte løsningene og se poeng og plassering på brettet.")],
      "disclaimer": "Wordfeud Solver er en uavhengig app og er ikke tilknyttet eller godkjent av skaperne av Wordfeud.",
      "faq": [("Må jeg skrive inn bokstavene mine?", "Nei. Ta et skjermbilde i Wordfeud, så leser appen både brettet og brikkene dine automatisk."),
              ("Virker den på iPhone og Android?", "Ja. Wordfeud Solver finnes i App Store og på Google Play."),
              ("Virker den med norsk ordliste?", "Du velger ordlisten som passer språket i Wordfeud-spillet ditt, i appens innstillinger."),
              ("Er Wordfeud Solver gratis?", None)],
    },
  },
  "words-with-friends-solver": {
    "name": "Words With Friends Solver", "cls": "wwf", "img": "wwf", "os": "Android, iOS",
    "gp": "https://play.google.com/store/apps/details?id=com.deepinkcode.wordswithfriendssolver",
    "as": "https://apps.apple.com/app/words-solver-friend/id6755461445",
    "video": "1MQpaBbKVww",
    "shots_localized": {},
    "game": "Words With Friends",
    "en": {
      "title": "Words With Friends Solver & Cheat – Best Words by Score",
      "desc": "Words With Friends Solver – a WWF cheat and word finder – reads your board from a screenshot and shows the highest-scoring words and where to play them. iPhone & Android.",
      "tagline": "Scan your Words With Friends board and get the best words, ranked by score.",
      "intro": "Words With Friends Solver scans your game board with OCR, analyzes it with an up-to-date dictionary and shows the highest-scoring words with clear instructions on where to place them. Supports English, French and Spanish dictionaries.",
      "extra": "It works as a Words With Friends cheat, WWF helper and word finder in one: no typing in your letters, just a screenshot. You get the best words for your exact board and rack, sorted by score.",
      "note": "On the App Store the app is called “Words Solver Friend”.",
      "shots": ["Find the best word", "See your highest-scoring moves", "Import your board", "See the tiles left"],
      "steps": [("Take a screenshot", "Take a screenshot of your board in Words With Friends. Turning off animated tiles gives the best recognition."),
                ("Import the screenshot", "Open the solver. Your latest screenshot is imported automatically, or tap “Import” to choose one."),
                ("Play the best word", "See the solutions ranked by points and exactly where each word goes.")],
      "disclaimer": "Words With Friends Solver is an independent app and is not affiliated with or endorsed by the makers of Words With Friends.",
      "faq": [("Do I have to type in my letters?", "No. Take a screenshot in Words With Friends and the solver reads both the board and your rack automatically."),
              ("Does it work on iPhone and Android?", "Yes. It is on Google Play as Words With Friends Solver and on the App Store as “Words Solver Friend”."),
              ("Which dictionaries are supported?", "English, French and Spanish."),
              ("Is it free?", None)],
    },
    "da": {
      "title": "Words With Friends Solver – find de bedste ord (WWF)",
      "desc": "Words With Friends Solver læser dit bræt fra et skærmbillede og viser de ord, der giver flest point, og hvor de skal ligge. WWF-hjælper til iPhone og Android.",
      "tagline": "Scan dit Words With Friends-bræt og få de bedste ord, sorteret efter point.",
      "intro": "Words With Friends Solver scanner dit bræt med OCR, analyserer det med en opdateret ordbog og viser de ord, der giver flest point, med tydelig placering på brættet. Understøtter engelsk, fransk og spansk ordbog.",
      "extra": "Den er WWF-hjælper og ordfinder i én: Du skal ikke taste bogstaver ind, bare tage et skærmbillede. Du får de bedste ord til netop dit bræt og dine brikker, sorteret efter point.",
      "note": "I App Store hedder appen “Words Solver Friend”.",
      "shots": ["Find det bedste ord", "Se dine træk med flest point", "Importér dit bræt", "Se brikker tilbage"],
      "steps": [("Tag et skærmbillede", "Tag et skærmbillede af brættet i Words With Friends. Slå animerede brikker fra for den bedste genkendelse."),
                ("Importér skærmbilledet", "Åbn appen. Dit seneste skærmbillede importeres automatisk, eller tryk på “Importér” for at vælge et."),
                ("Spil det bedste ord", "Se løsningerne sorteret efter point og præcis hvor hvert ord skal ligge.")],
      "disclaimer": "Words With Friends Solver er en uafhængig app og er ikke tilknyttet eller godkendt af udviklerne af Words With Friends.",
      "faq": [("Skal jeg taste mine bogstaver ind?", "Nej. Tag et skærmbillede i Words With Friends, så læser appen både brættet og dine brikker automatisk."),
              ("Virker den på iPhone og Android?", "Ja. Den hedder Words With Friends Solver på Google Play og “Words Solver Friend” i App Store."),
              ("Hvilke ordbøger understøttes?", "Engelsk, fransk og spansk."),
              ("Er den gratis?", None)],
    },
    "nl": {
      "title": "Words With Friends Solver – hulp en woordzoeker (WWF)",
      "desc": "Words With Friends Solver leest je bord uit een screenshot en toont de woorden met de meeste punten en waar je ze legt. WWF hulp en woordzoeker voor iPhone en Android.",
      "tagline": "Scan je Words With Friends-bord en krijg de beste woorden, gesorteerd op punten.",
      "intro": "Words With Friends Solver scant je bord met OCR, analyseert het met een actuele woordenlijst en toont de woorden met de meeste punten, met duidelijke instructies waar je ze legt. Ondersteunt Engelse, Franse en Spaanse woordenlijsten.",
      "extra": "WWF hulp, woordzoeker en cheat in één: je hoeft geen letters in te typen, alleen een screenshot te maken. Je krijgt de beste woorden voor precies jouw bord en letters, gesorteerd op punten.",
      "note": "In de App Store heet de app “Words Solver Friend”.",
      "shots": ["Vind het beste woord", "Bekijk de zetten met de meeste punten", "Importeer je bord", "Bekijk de resterende letters"],
      "steps": [("Maak een screenshot", "Maak een screenshot van je bord in Words With Friends. Zet geanimeerde letters uit voor de beste herkenning."),
                ("Importeer het screenshot", "Open de app. Je nieuwste screenshot wordt automatisch geïmporteerd, of tik op “Importeren” om er een te kiezen."),
                ("Speel het beste woord", "Bekijk de oplossingen gesorteerd op punten en precies waar elk woord komt.")],
      "disclaimer": "Words With Friends Solver is een onafhankelijke app en is niet verbonden aan of goedgekeurd door de makers van Words With Friends.",
      "faq": [("Moet ik mijn letters intypen?", "Nee. Maak een screenshot in Words With Friends en de app leest zowel het bord als je letters automatisch."),
              ("Werkt het op iPhone en Android?", "Ja. Op Google Play heet de app Words With Friends Solver en in de App Store “Words Solver Friend”."),
              ("Welke woordenlijsten worden ondersteund?", "Engels, Frans en Spaans."),
              ("Is de app gratis?", None)],
    },
    "sv": {
      "title": "Words With Friends Solver – hitta de bästa orden (WWF)",
      "desc": "Words With Friends Solver läser din spelplan från en skärmbild och visar orden som ger flest poäng och var de ska läggas. WWF-hjälp och ordfinnare för iPhone och Android.",
      "tagline": "Skanna din Words With Friends-plan och få de bästa orden, sorterade efter poäng.",
      "intro": "Words With Friends Solver skannar din spelplan med OCR, analyserar den med en uppdaterad ordlista och visar orden som ger flest poäng, med tydlig placering på spelplanen. Stöder engelska, franska och spanska ordlistor.",
      "extra": "WWF-hjälp, ordfinnare och fusk-app i ett: du behöver inte skriva in bokstäver, bara ta en skärmbild. Du får de bästa orden för just din spelplan och dina brickor, sorterade efter poäng.",
      "note": "I App Store heter appen ”Words Solver Friend”.",
      "shots": ["Hitta det bästa ordet", "Se dragen med flest poäng", "Importera din spelplan", "Se brickor kvar"],
      "steps": [("Ta en skärmbild", "Ta en skärmbild av spelplanen i Words With Friends. Stäng av animerade brickor för bäst igenkänning."),
                ("Importera skärmbilden", "Öppna appen. Din senaste skärmbild importeras automatiskt, eller tryck på ”Importera” för att välja en."),
                ("Spela det bästa ordet", "Se lösningarna sorterade efter poäng och exakt var varje ord ska ligga.")],
      "disclaimer": "Words With Friends Solver är en fristående app och är inte knuten till eller godkänd av skaparna av Words With Friends.",
      "faq": [("Måste jag skriva in mina bokstäver?", "Nej. Ta en skärmbild i Words With Friends så läser appen både spelplanen och dina brickor automatiskt."),
              ("Fungerar den på iPhone och Android?", "Ja. Den heter Words With Friends Solver på Google Play och ”Words Solver Friend” i App Store."),
              ("Vilka ordlistor stöds?", "Engelska, franska och spanska."),
              ("Är den gratis?", None)],
    },
    "no": {
      "title": "Words With Friends Solver – finn de beste ordene (WWF)",
      "desc": "Words With Friends Solver leser brettet ditt fra et skjermbilde og viser ordene som gir flest poeng og hvor de skal legges. WWF-hjelp og ordfinner for iPhone og Android.",
      "tagline": "Skann Words With Friends-brettet ditt og få de beste ordene, sortert etter poeng.",
      "intro": "Words With Friends Solver skanner brettet ditt med OCR, analyserer det med en oppdatert ordliste og viser ordene som gir flest poeng, med tydelig plassering på brettet. Støtter engelske, franske og spanske ordlister.",
      "extra": "WWF-hjelp, ordfinner og juksehjelp i ett: du trenger ikke skrive inn bokstaver, bare ta et skjermbilde. Du får de beste ordene for akkurat ditt brett og dine brikker, sortert etter poeng.",
      "note": "I App Store heter appen «Words Solver Friend».",
      "shots": ["Finn det beste ordet", "Se trekkene med flest poeng", "Importer brettet ditt", "Se brikker igjen"],
      "steps": [("Ta et skjermbilde", "Ta et skjermbilde av brettet i Words With Friends. Slå av animerte brikker for best gjenkjenning."),
                ("Importer skjermbildet", "Åpne appen. Det siste skjermbildet ditt importeres automatisk, eller trykk på «Importer» for å velge et."),
                ("Spill det beste ordet", "Se løsningene sortert etter poeng og nøyaktig hvor hvert ord skal ligge.")],
      "disclaimer": "Words With Friends Solver er en uavhengig app og er ikke tilknyttet eller godkjent av skaperne av Words With Friends.",
      "faq": [("Må jeg skrive inn bokstavene mine?", "Nei. Ta et skjermbilde i Words With Friends, så leser appen både brettet og brikkene dine automatisk."),
              ("Virker den på iPhone og Android?", "Ja. Den heter Words With Friends Solver på Google Play og «Words Solver Friend» i App Store."),
              ("Hvilke ordlister støttes?", "Engelsk, fransk og spansk."),
              ("Er den gratis?", None)],
    },
  },
  "scrabble-go-cheat": {
    "name": "Scrabble GO Cheat", "cls": "scrabble", "img": "scrabble", "os": "Android",
    "gp": "https://play.google.com/store/apps/details?id=com.deepinkcode.scrabblegocheat",
    "as": None,
    "video": None,
    "shots_localized": {},
    "game": "Scrabble GO",
    "en": {
      "title": "Scrabble GO Cheat – Word Finder for the Highest Score",
      "desc": "Scrabble GO Cheat reads your board from a screenshot and shows the highest-scoring words and where to place them. A Scrabble GO helper and word finder for Android.",
      "tagline": "Your shortcut to the best words in Scrabble GO.",
      "intro": "Scrabble GO Cheat scans your Scrabble GO board with OCR, analyzes it with updated dictionaries and a powerful solving algorithm, and shows the best possible words ranked by score, with clear placement on the board. English and French dictionaries.",
      "extra": "Use it as a Scrabble GO helper and word finder: no typing in letters, just a screenshot. You get the best Scrabble GO words for your exact board and rack, sorted by score.",
      "note": "Currently available for Android only.",
      "shots": ["Best moves ranked by points", "Tiles left in the game", "Settings and dictionary"],
      "steps": [("Take a screenshot", "Take a screenshot of your board in Scrabble GO."),
                ("Import the screenshot", "Open Scrabble GO Cheat. Your latest screenshot is imported automatically, or tap “Import” to choose one."),
                ("Pick your word", "Browse the ranked solutions and see where to place each word.")],
      "disclaimer": "Scrabble GO Cheat is an independent app and is not affiliated with or endorsed by the makers of Scrabble GO.",
      "faq": [("Do I have to type in my letters?", "No. Take a screenshot in Scrabble GO and the app reads both the board and your rack automatically."),
              ("Does it work on iPhone?", "Not yet. Scrabble GO Cheat is currently available for Android on Google Play."),
              ("Which dictionaries are supported?", "English and French."),
              ("Is it free?", None)],
    },
    "da": {
      "title": "Scrabble GO Cheat – find ordene med flest point",
      "desc": "Scrabble GO Cheat læser dit bræt fra et skærmbillede og viser de ord, der giver flest point, og hvor de skal ligge. Scrabble GO-hjælper og ordfinder til Android.",
      "tagline": "Din genvej til de bedste ord i Scrabble GO.",
      "intro": "Scrabble GO Cheat scanner dit Scrabble GO-bræt med OCR, analyserer det med opdaterede ordbøger og en effektiv algoritme og viser de bedste ord sorteret efter point, med tydelig placering på brættet. Engelsk og fransk ordbog.",
      "extra": "Brug den som Scrabble GO-hjælper og ordfinder: Du skal ikke taste bogstaver ind, bare tage et skærmbillede. Du får de bedste ord til netop dit bræt og dine brikker, sorteret efter point.",
      "note": "Findes i øjeblikket kun til Android.",
      "shots": ["Bedste træk sorteret efter point", "Brikker tilbage i spillet", "Indstillinger og ordbog"],
      "steps": [("Tag et skærmbillede", "Tag et skærmbillede af brættet i Scrabble GO."),
                ("Importér skærmbilledet", "Åbn Scrabble GO Cheat. Dit seneste skærmbillede importeres automatisk, eller tryk på “Importér” for at vælge et."),
                ("Vælg dit ord", "Bladr gennem de rangerede løsninger og se, hvor hvert ord skal ligge.")],
      "disclaimer": "Scrabble GO Cheat er en uafhængig app og er ikke tilknyttet eller godkendt af udviklerne af Scrabble GO.",
      "faq": [("Skal jeg taste mine bogstaver ind?", "Nej. Tag et skærmbillede i Scrabble GO, så læser appen både brættet og dine brikker automatisk."),
              ("Virker den på iPhone?", "Ikke endnu. Scrabble GO Cheat findes i øjeblikket til Android på Google Play."),
              ("Hvilke ordbøger understøttes?", "Engelsk og fransk."),
              ("Er den gratis?", None)],
    },
    "nl": {
      "title": "Scrabble GO Cheat – Scrabble GO hulp en woordzoeker",
      "desc": "Scrabble GO Cheat leest je bord uit een screenshot en toont de woorden met de meeste punten en waar je ze legt. Scrabble GO hulp en woordzoeker voor Android.",
      "tagline": "Je snelste weg naar de beste woorden in Scrabble GO.",
      "intro": "Scrabble GO Cheat scant je Scrabble GO-bord met OCR, analyseert het met actuele woordenlijsten en een krachtig algoritme en toont de best mogelijke woorden gesorteerd op punten, met duidelijke plaatsing op het bord. Engelse en Franse woordenlijsten.",
      "extra": "Gebruik het als Scrabble GO hulp en woordzoeker: geen letters intypen, alleen een screenshot. Je krijgt de beste Scrabble GO-woorden voor precies jouw bord en letters, gesorteerd op punten.",
      "note": "Momenteel alleen beschikbaar voor Android.",
      "shots": ["Beste zetten gesorteerd op punten", "Resterende letters in het spel", "Instellingen en woordenlijst"],
      "steps": [("Maak een screenshot", "Maak een screenshot van je bord in Scrabble GO."),
                ("Importeer het screenshot", "Open Scrabble GO Cheat. Je nieuwste screenshot wordt automatisch geïmporteerd, of tik op “Importeren” om er een te kiezen."),
                ("Kies je woord", "Blader door de gesorteerde oplossingen en zie waar je elk woord legt.")],
      "disclaimer": "Scrabble GO Cheat is een onafhankelijke app en is niet verbonden aan of goedgekeurd door de makers van Scrabble GO.",
      "faq": [("Moet ik mijn letters intypen?", "Nee. Maak een screenshot in Scrabble GO en de app leest zowel het bord als je letters automatisch."),
              ("Werkt het op iPhone?", "Nog niet. Scrabble GO Cheat is momenteel beschikbaar voor Android op Google Play."),
              ("Welke woordenlijsten worden ondersteund?", "Engels en Frans."),
              ("Is de app gratis?", None)],
    },
    "sv": {
      "title": "Scrabble GO Cheat – hitta orden med flest poäng",
      "desc": "Scrabble GO Cheat läser din spelplan från en skärmbild och visar orden som ger flest poäng och var de ska läggas. Scrabble GO-hjälp och ordfinnare för Android.",
      "tagline": "Din genväg till de bästa orden i Scrabble GO.",
      "intro": "Scrabble GO Cheat skannar din Scrabble GO-plan med OCR, analyserar den med uppdaterade ordlistor och en kraftfull algoritm och visar de bästa möjliga orden sorterade efter poäng, med tydlig placering på spelplanen. Engelska och franska ordlistor.",
      "extra": "Använd den som Scrabble GO-hjälp och ordfinnare: inga bokstäver att skriva in, bara en skärmbild. Du får de bästa Scrabble GO-orden för just din spelplan och dina brickor, sorterade efter poäng.",
      "note": "Finns för närvarande bara för Android.",
      "shots": ["Bästa dragen sorterade efter poäng", "Brickor kvar i spelet", "Inställningar och ordlista"],
      "steps": [("Ta en skärmbild", "Ta en skärmbild av spelplanen i Scrabble GO."),
                ("Importera skärmbilden", "Öppna Scrabble GO Cheat. Din senaste skärmbild importeras automatiskt, eller tryck på ”Importera” för att välja en."),
                ("Välj ditt ord", "Bläddra bland de sorterade lösningarna och se var varje ord ska ligga.")],
      "disclaimer": "Scrabble GO Cheat är en fristående app och är inte knuten till eller godkänd av skaparna av Scrabble GO.",
      "faq": [("Måste jag skriva in mina bokstäver?", "Nej. Ta en skärmbild i Scrabble GO så läser appen både spelplanen och dina brickor automatiskt."),
              ("Fungerar den på iPhone?", "Inte än. Scrabble GO Cheat finns för närvarande för Android på Google Play."),
              ("Vilka ordlistor stöds?", "Engelska och franska."),
              ("Är den gratis?", None)],
    },
    "no": {
      "title": "Scrabble GO Cheat – finn ordene med flest poeng",
      "desc": "Scrabble GO Cheat leser brettet ditt fra et skjermbilde og viser ordene som gir flest poeng og hvor de skal legges. Scrabble GO-hjelp og ordfinner for Android.",
      "tagline": "Din snarvei til de beste ordene i Scrabble GO.",
      "intro": "Scrabble GO Cheat skanner Scrabble GO-brettet ditt med OCR, analyserer det med oppdaterte ordlister og en kraftig algoritme og viser de best mulige ordene sortert etter poeng, med tydelig plassering på brettet. Engelske og franske ordlister.",
      "extra": "Bruk den som Scrabble GO-hjelp og ordfinner: ingen bokstaver å skrive inn, bare et skjermbilde. Du får de beste Scrabble GO-ordene for akkurat ditt brett og dine brikker, sortert etter poeng.",
      "note": "Finnes foreløpig bare for Android.",
      "shots": ["Beste trekk sortert etter poeng", "Brikker igjen i spillet", "Innstillinger og ordliste"],
      "steps": [("Ta et skjermbilde", "Ta et skjermbilde av brettet i Scrabble GO."),
                ("Importer skjermbildet", "Åpne Scrabble GO Cheat. Det siste skjermbildet ditt importeres automatisk, eller trykk på «Importer» for å velge et."),
                ("Velg ordet ditt", "Bla gjennom de sorterte løsningene og se hvor hvert ord skal ligge.")],
      "disclaimer": "Scrabble GO Cheat er en uavhengig app og er ikke tilknyttet eller godkjent av skaperne av Scrabble GO.",
      "faq": [("Må jeg skrive inn bokstavene mine?", "Nei. Ta et skjermbilde i Scrabble GO, så leser appen både brettet og brikkene dine automatisk."),
              ("Virker den på iPhone?", "Ikke ennå. Scrabble GO Cheat finnes foreløpig for Android på Google Play."),
              ("Hvilke ordlister støttes?", "Engelsk og fransk."),
              ("Er den gratis?", None)],
    },
  },
}
